from .SHARED import CONSISTENCY_ERROR_DESC, CROSS_FILE_NOTE, FOOTER, FORMAT_DESC, NOTE, TASK
from .EXEMPLARS import GOOD_EXAMPLES, COT_EXAMPLES, BAD_EXAMPLES

BASIC_STYLE_ANALYSIS_PROMPT = f"""
{TASK}

Your main focus is to find consistency issues. 

{CONSISTENCY_ERROR_DESC}

{FORMAT_DESC}

{NOTE}

------ BEGIN EXAMPLES --------

{GOOD_EXAMPLES}

{COT_EXAMPLES}

------ END EXAMPLES -----------

------ BEGIN BAD EXAMPLES [ DONT DO THIS ] --------

{BAD_EXAMPLES}

------ END BAD EXAMPLES [ DONT DO THIS ] -----------


{FOOTER}
"""

CROSS_FILE_STYLE_ANALYSIS_PROMPT = f"""
{TASK}

Your main focus is finding consistency errors. 

{CONSISTENCY_ERROR_DESC}

{FORMAT_DESC}

{CROSS_FILE_NOTE}

{NOTE}

------ BEGIN EXAMPLES --------

{GOOD_EXAMPLES}

{COT_EXAMPLES}

------ END EXAMPLES -----------

------ BEGIN BAD EXAMPLES [ DONT DO THIS ] --------

{BAD_EXAMPLES}

------ END BAD EXAMPLES [ DONT DO THIS ] -----------

{FOOTER}
"""
