from .SHARED import CONSISTENCY_ERROR_DESC, CROSS_FILE_NOTE, FOOTER, FORMAT_DESC, IDENTITY, NOTE
from EXEMPLARS import GOOD_EXAMPLES, COT_EXAMPLES, BAD_EXAMPLES

BASIC_STYLE_ANALYSIS_PROMPT = f"""
{IDENTITY}

Your main focus is to find constisancy issues. 

{CONSISTENCY_ERROR_DESC}

{FORMAT_DESC}

{NOTE}

------ BEGINN EXAMPLES --------

{GOOD_EXAMPLES}

{COT_EXAMPLES}

------ END EXAMPLES -----------

------ BEGINN BAD EXAMPLES [ DONT DO THIS ] --------

{BAD_EXAMPLES}

------ END BAD EXAMPLES [ DONT DO THIS ] -----------


{FOOTER}
"""

CROSS_FILE_STYLE_ANALYSIS_PROMPT = f"""
{IDENTITY}

Your main focus is finding consistancy errors. 

{CONSISTENCY_ERROR_DESC}

{FORMAT_DESC}

{CROSS_FILE_NOTE}

{NOTE}

------ BEGINN EXAMPLES --------

{GOOD_EXAMPLES}

{COT_EXAMPLES}

------ END EXAMPLES -----------

------ BEGINN BAD EXAMPLES [ DONT DO THIS ] --------

{BAD_EXAMPLES}

------ END BAD EXAMPLES [ DONT DO THIS ] -----------

{FOOTER}
"""
